fix: useSnapshot
nanxiaobei/resso pull request #19
Opened 2024-01-15 08:31 UTC by solarhell

2024-01-15 09:28 UTC, nanxiaobei commented
acroding to the doc, the 3rd param is `getServerSnapshot`?

https://react.dev/reference/react/useSyncExternalStore

2024-01-16 00:20 UTC, himself65 requested changes

2024-01-16 00:20 UTC, himself65 commented on src/index.ts
> -          state[key].getSnapshot
this doesn't seem right, third parameter is for server-side snapshot

2024-01-16 00:20 UTC, himself65 commented on src/index.ts
> -          state[key].getSnapshot
https://react.dev/reference/react/useSyncExternalStore#adding-support-for-server-rendering

2024-01-25 06:46 UTC, closed without merging